version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.32
    container_name: jaeger
    ports:
      - 16686:16686
      - 14268:14268
    networks:
      - uber

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jaeger-test-api
    depends_on:
      - jaeger
    environment:
      - JAEGER_SERVICE_NAME=uber-api
      - JAEGER_URL=http://jaeger:14268/api/traces
      - ENVIRONMENT=development
    ports:
      - 8080:8080
    networks:
      - uber

networks:
  uber:
    driver: bridge