version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.18
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - uber

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jaeger-test-api
    depends_on:
      - jaeger
    ports:
      - 5000:5000
    networks:
      - uber

networks:
  uber:
    driver: bridge