version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.32
    container_name: jaeger
    ports:
      - 16686:16686
      - 14268:14268
    networks:
      - uber

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jaeger-test-api
    depends_on:
      - jaeger
    ports:
      - 5000:5000
    networks:
      - uber

networks:
  uber:
    driver: bridge