apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: jaeger-collector
  ports:
    - protocol: TCP
      port: 14268
      targetPort: 14268