apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query-deployment
  namespace: default
  labels:
    app: jaeger-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-query
  template:
    metadata:
      labels:
        app: jaeger-query
    spec:
      containers:
      - name: jaeger-query
        image: jaegertracing/jaeger-query:1.32
        ports:
        - containerPort: 14268
        - containerPort: 14269
        env:
          - name: "SPAN_STORAGE_TYPE"
            value: "elasticsearch"
        args: ["--es.server-urls=http://elasticsearch-service:9200"]
        # nodeSelector:
        #   node_group: monitoring-ng
