apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: jaeger-query
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686